language: python
dist: xenial
sudo: false

services:
  - xvfb

addons:
    apt:
      packages:
        - herbstluftwm
        - libxkbcommon-x11-0

env: 
   global:
      - OFFICIAL_REPO="klauer/qtpynodeeditor"
      # Doctr deploy key for klauer/qtpynodeeditor
      - secure: "gXB0qZy/xd9U7RYKWexhqzmWR6SJzQ+YI3QjNuBBRc2ZprottF+V2+nX0kTtacYvSBilIdsKaF9qm2Xr0yvRynMLiSyU9IDRCFEiBVJQcMZUD+2EO69hDUmxLDf5w29aCEZfpNdzEx0InWBU4YctaWbLandwvPH7uI/wsWYPHPUewabpp5m2b5UBGvUswYvbBCZF5Mu+/DoAHVeJfJ2nA07BqsdpK5JHX1i+Q9JgZqC4u9o4wDtdGevhhSaMiywZWc/MjJFb50QPCOV9Ad7z2HusF9cuuJG4H2d+7wIqfOb89OxUoyrFS2TqdEltbkc+j7vqkqrEGKJIIPIMj6STHUc/RSRg+MFgpX19r1/sbP3RfWXYqBEIlokAFPw/LUo5lyyrphy4zg7PWRvLZbtx9dY/30W6PG2ZPHZiX247r9VeRlLHOWSXfw+uUNE6QzkqvsChCOOpA3WUcG+5QgZGYTaK+5PkeFI+6/+Dh9TZjwlsFa8YuOBHeeDQGXBvz9bsFPkhT8MZkJNXiB4FWVYucbERUsqmsNhk/XvGBKRjkbZoDyqONWWaOHvAIdBTNrko+M7yMpDhKol0azTAwJhT4lwtjsAsn37bq7F7zoOOmJj9NVMSt97IP+yBPfIr70JYtVxvuVTrTyfb55LCg3KMaMujk2p2KCR7AGoerj/Sx/s="

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

matrix:
  include:
    - python: 3.6
      env:
        - CONDA_UPLOAD=1
        - BUILD_DOCS=1
    - python: 3.7


install:
  # Install and configure miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no

  # Ensure all packages are up-to-date
  - conda update -q conda
  - conda install conda-build anaconda-client
  - conda config --append channels conda-forge
  - conda info -a

  # Build the conda recipe for this package
  - conda build -q conda-recipe --python=$TRAVIS_PYTHON_VERSION --output-folder bld-dir
  - conda config --add channels "file://`pwd`/bld-dir"

  # Create the test environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION qtpynodeeditor --file requirements.txt
  - source deactivate
  - source activate test-environment

  # Install additional development requirements
  - pip install -Ur dev-requirements.txt
  # Install the package
  - pip install -e .


before_script:
  # Run the window manager
  - "herbstluftwm &"
  - sleep 1


script:
  - flake8 qtpynodeeditor
  - coverage run run_tests.py
  - set -e
  
  - |
    if [[ "$BUILD_DOCS" == "1" ]]; then
      # Create HTML documentation  
      pushd docs
      make html
      popd
      #Publish docs.
      doctr deploy . --built-docs docs/build/html --deploy-branch-name gh-pages --command "touch .nojekyll; git add .nojekyll"
    fi
   

after_success:
  - coverage report -m
  - codecov

  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == $OFFICIAL_REPO && "$CONDA_UPLOAD" == "1" ]]; then
      if [[ $TRAVIS_BRANCH == $TRAVIS_TAG  && $TRAVIS_TAG != '' ]]; then
        export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN_TAG
        anaconda upload bld-dir/linux-64/*.tar.bz2
      fi
    fi
